name: schedule_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: ^3.1.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  modal_progress_hud: ^0.1.3
  provider: ^4.3.3
  ml_algo: ^15.6.3
  ml_dataframe: ^0.4.0
  ml_preprocessing: ^5.2.2
  flutter_local_notifications: ^4.0.1+1
  background_fetch: ^0.7.1
  page_transition: ^1.1.7+6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
  - images/
  fonts:
    - family: Coiny
      fonts:
        - asset: lib/fonts/Coiny-Regular.ttf
    - family: FugazOne
      fonts:
        - asset: lib/fonts/FugazOne-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: lib/fonts/Lalezar-Regular.ttf
